[workspace]
resolver = "3"
members = [
  "packages/wayland-client",
  "packages/wayland-client-core",
  "packages/wayland-client-protocol",
  "packages/wayland-server",
  "packages/wayland-server-core",
  "packages/wayland-server-protocol",
  "packages/wayland-scanner",
]
