[package]
name = "wayland-client"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client-core = { path = "../wayland-client-core" }
wayland-client-protocol = { path = "../wayland-client-protocol" }
wayland-scanner = { path = "../wayland-scanner" }
