[package]
name = "wayland-scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.37.5", features = ["serde", "serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
syn = { version = "2.0.101", features = ["parsing"] }
